baseURL = 'https://cairo-nlp.github.io/'
languageCode = 'en-us'
title = 'Cairo NLP'

theme = "nightfall"
[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"
  [[menu.header]]
    name = "talks"
    weight = 1
    url = "talks"
  [[menu.header]]
    name = "paper-map"
    weight = 2
    url = "paper-map"


[params]
user = "cairo nlp"
hostname = "io"

  [params.author]
    name = "cAIro|NLP Group"
    email = "cairo.nlp.group@gmail.com"


[[params.social]]
key = 0
name = "github"
url = "https://github.com/Cairo-NLP"

target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO

[[params.social]]
key = 1
name = "email"
url = "mailto:cairo.nlp.group@gmail.com"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true